# This is a config file for the piccr package

file_extension: "*.csv"	          # file extension used for data files
input_directory:  data            # directory with the measurement data to be calibrated
output_directory: calibrated_data # output directory for the calibrated data
calibration_method:	2		        	# set type of desired calibration: flag=1->drift-correction+three-point calibration/flag=2->double three-point calibration
use_memory_correction:	yes			  # signal memory correction: yes/no
include_standards_in_output:	no	# format of desired csv-file output: flag=no->only output sample data/flag=yes->output standard and sample data in original order

standards:
  - name: KARA
    O18_True: -0.10
    H2_True: -0.6
    use_for_memory_correction: no
    use_for_drift_correction: no
    use_for_calibration: no
  - name: DML
    o18_True: -42.50
    H2_True: -341.0
    use_for_memory_correction: yes
    use_for_drift_correction: yes
    use_for_calibration: yes
  - name: TD1
    o18_True: -33.90
    H2_True: -266.2
    use_for_memory_correction: yes
    use_for_drift_correction: yes
    use_for_calibration: yes
  - name: JASE
    o18_True: -50.22
    H2_True: -392.5
    use_for_memory_correction: yes
    use_for_drift_correction: yes
    use_for_calibration: yes
  - name: NGT
    o18_True: -34.40
    H2_True: -265.5
    use_for_memory_correction: no
    use_for_drift_correction: no
    use_for_calibration: no
